### ISSUE TITLE
Multiple input folders are confusing

### ISSUE THREAD

**Issue by Janekdererste** [matsim-scenarios/matsim-berlin#131]
This scenario has both a _scenario_ and an _input_ folder. The _input_ folder contains files for v5.x. I would suggest keeping only the input folder. Possibly, the README could directly point into that folder. It is not apparent, from the README, where to search for input files.

**Comment by rakow** [comment]
You are right, there is this old folder `scenarios` that is not needed anymore. However the README prominently points to the correct input folder 
<img width="889" alt="grafik" src="https://github.com/user-attachments/assets/959b3a1f-9079-47c4-bdee-cbc71b1c952d">
