### ISSUE TITLE
congested mode

### ISSUE THREAD

**Issue by jinkai89** [matsim-scenarios/matsim-berlin#17]
What is the difference of creating a congested through the following code

controler.addOverridingModule( new AbstractModule() {
			@Override
			public void install() {
				addTravelTimeBinding( TransportMode.ride ).to( networkTravelTime() );
				addTravelDisutilityFactoryBinding( TransportMode.ride ).to( carTravelDisutilityFactoryKey() );
			}
		} );

and by adding a teleported mode in the config file like the following:

 
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="ride" />
			<param name="teleportedModeSpeed" value="3.1388889" />
		</parameterset>

From what I undestand, in both cases, the mode 'ride' are teleported?

**Comment by ikaddoura** [comment]
Yes, in both ways, 'ride' agents will be teleported.

The first approach sets the travel time for 'ride' equal to the travel time for 'car'. Thus, the 'ride' mode is a congested mode (in case there is traffic congestion within the 'car' mode).

The second approach only takes into consideration the beeline distance factor and a fixed mode speed. There will be no reduced travel speeds during peak times.

For the Berlin scenario, we decided to use the first approach.

**Comment by jinkai89** [comment]
How the travel time is calculated in the first case? 

From What I understand, travel time is dependent on the link capacity. How can the you obtain accurate congested travel travel if you don't route the mode on the actual network?

**Comment by ikaddoura** [comment]
The travel time results from the link capacity and freespeed as well as number/type of vehicles per road segment and time bin.
MATSim stores the average travel time per road segment and time bin from previous iterations which can then be used for routing (even if the mode is not simulated as a network mode in the qsim).
