### ISSUE TITLE
Integrating Matsim and Cadyts

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-scenarios/matsim-berlin#18]
I’m trying to create a MATSim scenario for my case study. I was looking at the works regarding the integration of Cadyts with MATSim for the calibration of the travel demand, and I had some question:
-Firstly, in relation to the scaling up of the network properties, how’s made?
-Secondly, how did you group all different plans from CEMDAP into a list for every agent?
-Lastly, what method did you use to calculate zonal parameters and zone2zone infos to put in CEMDAP, since I’m quite new, I would like to know if thhere’s a fast method to get the infos.
Hope you can help with questions, thanks for the attention,
Best Regards

**Comment by ikaddoura** [comment]
1) First, the flow and storage capacity factor in the qsim config group has to be set correctly. For a 1 pct sample of the population the parameters are set to 0.01; for a 10 pct population sample the parameters are set to 0.1. If you use cadyts, in the counts config group, there should be something like a scaling factor (countsScaleFactor) which has to be set following the same logic.

2) Each person keeps all different plans which come from CEMDAP. Then, we switch on Cadyts and let each agent decide for him/herself what plan to keep. By doing that, each agent keeps the plan which on the one hand makes sense for the agent and on the other hand contributes to the overall traffic count statistics. Finally, the selected plans are extracted and used as input plans for future simulation runs, that is, activity locations and activity-trip-patterns are fixed. For a detailed description, see here: https://svn.vsp.tu-berlin.de/repos/public-svn/publications/vspwp/2019/19-01/ZiemkeEtAl2019OpenBerlinScenarioVSPWP.pdf

3) I don't know if I understand you correctly. For the CEMDAP computation, we mainly use default parameters and relatively simple calculations (e.g. of the travel time) from centroids to centroids.

**Comment by MAlbertini95** [comment]
Thank you for the answer, it's been very useful.
So I generated the population/plans.xml .. I wonder if you could please tell me how to practically integrate Cadyts and Matsim: as I understood I have to copy add the dependency in the pom.xml file and then?
Lastly, which is the best tool for considering AV taxis and analysing the output? Are there any other modules useful for simulating traffic/managing the taxi service?
Thank you and Best Regards

**Comment by whizkid-25** [comment]
Hi @MAlbertini95 

Were you able to integrate Cadyts with MATSim?

**Comment by ikaddoura** [comment]
I guess this discussion was continued here: matsim-org/matsim-code-examples#201
