### ISSUE TITLE
Cadyts Multiplans calibration

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-scenarios/matsim-berlin#21]
Dear Berlin scenario crew,
I’m trying to build a scenario for my thesis, so I choose a case study: by now, I have extracted the xml network from OSM. For Demand construction, I used PopGen and Actitopp to generate a set of 5 plans for agent, which now I have to translate in .xml format. What I would like to do is then calibrate this plans with traffic counts using Cadyts. For constructing the plans, I had a commuter matrix representing the city at 12 zones ( not too big as the city is 112k residents) and according to this matrix, I assigned random commuting destinations using Traffic Zones ( desired resolution ), coherent with upper spatial resolution, but still to be calibrated thoroughly; later I draw casual coordinates by overlapping Traffic Zone data and Land use data. So I’d like to calibrate this set of 5 plans in order to represents real situation.
My question are:
• Is this idea feasible?
• Do you have a population.xml file with different plans to use as reference? ( Do I have to set as just one schedule? )
• How about modes, in your pubblications I read about the integration, is it necessary to set at first only cars?
• And, last one, it would be interesting to simulate also <18 people, for whom by now I have the schedule, is this possible? I have some infos like the possession of license and age which I like to introduce in the population.xml file, is it possible to use them as conditions for choosing transport mode in MATSim?
Thank in advance, hope you can help.
Best Regards,

**Comment by dziemke** [comment]
* Yes, it sounds (at least in general) feasible.
* The multiple plans of a given agent, you need to collect within the agent, i.e. in the population XML you would have correspondingly multiple <plan ... </plan> sections inside each person (agent).
* No, it is my no means necessary to set first to cars only. This is just an approach which we used in one particular scenario set up as we only had count data for car. If you also do only have count data for car traffic, you *can* also use this approach as a simplifying solution, but (in general) it would be nicer to have different modes directly in the simulation with corresponding mode-specific counts.
* Sure, there is nothing what would prevent you form simulating people aged younger than 18. MATSim does not care about age :) You tell the agents what they want to do by providing them with the corresponding schedules. The fact that we excluded this age segment is that our synthetic population did not contain them. So, this is rather a limitation, but by no means a necessity. Regarding those conditions, you can take using so-called subpopulations into consideration.

**Comment by MAlbertini95** [comment]
Thank you for the answer, it's been very useful. 
So I generated the population/plans.xml .. I wonder if you could please tell me how to practically integrate Cadyts and Matsim: as I understood I have to copy add the dependency in the pom.xml file and then? 
Another question regarding the last 2 points: I have traffic data counts ( including some info about occupancy per vehicle), pt counts at stops and also walking crossing count at intersections. So which approach would be useful for calibrating modal/location choice? And as for children, as long as they mainly use "ride" mode, how can their trips be calibrated? 
Lastly, which is the best tool for analysing the output?
Thank you and Best Regards

**Comment by ikaddoura** [comment]
I guess this discussion was continued here: https://github.com/matsim-org/matsim-code-examples/issues/201

**Comment by Y-Yahyaoui** [comment]
Hi, I'm currently working on traffic simulation and noise pollution.
Can you tell me the steps used in generating the plans by popgen and translating them to .xml ?
