### ISSUE TITLE
Transfer demand model into SUMO traffic simulation software

### ISSUE THREAD

**Issue by marcelreppi** [matsim-scenarios/matsim-berlin#32]
Hello,

for the past couple days I have been trying to find ways to convert the MATSim output plans into a different format so that I can reuse them in the [SUMO Traffic Simulation](https://sumo.dlr.de/docs/index.html) software. SUMO has a different XML specification for networks and routes so therefore the data needs to be converted.

My first approach was to convert the MATSim output network using their tool [NETCONVERT](https://sumo.dlr.de/docs/NETCONVERT.html) and then manually parse the plans into the correct SUMO format.
The conversion works with some warnings but when trying to simulate the parsed MATSim plans I keep running into the issue that SUMO can't execute a plan because there is no connection between some of the edges. I assume this happens due to some automatic modifications to the network that made during the conversion process. Furthermore, the quality of the network data is reduced immensely as the converted network looks really weird in some areas/streets and does not really represent the reality.

My next approach is to use OSM data as my road network and somehow parse the edges/nodes from the MATSim output to match the locations in my OSM network. For this I need to convert the X and Y coordinates of the nodes from the output network into a CRS (WGS84) so that I can map the edges from the plans to my OSM edges.

Is this even possible? How could I do this?
Do you maybe have other ideas on how I could transfer the demand model?

I would be extremely thankful for any input!!
Best regards!

**Comment by ikaddoura** [comment]
Activities take place at coordinates, the link ID given in the plans file is probably the nearest link. Agents are then allowed to walk from the exact activity location to the nearest link of the correct subnetwork (here: car or public transit). Networks of different modes don't have to be connected. There are for example no links which connect public transit links and car links.

I would simply not (!) use the link IDs in the plans file. Instead: Only use the coordinates from the MATSim plans file and then find the nearest link in the correct (mode-filtered) subnetwork.
Have a look into the `NetworkUtils` and `MultimodalNetworkCleaner`...

**Comment by marcelreppi** [comment]
@ikaddoura Thank you very much for your response which has been very helpful!

**Comment by namdre** [comment]
Some comments:
- netconvert can import MATSim networks directly using option --matsim-files
- netconvert can also create MATSim networks from any of the supported input formats using option --matsim-out
- SUMO includes the tool matsim_importPlans.py (in tools/import/matsim) which can import matsim plans (either vehicles or vehicles and persons)
- the sumo and duarouter applications can import trip data that is specified in terms of xy or lonLat coordinates
