### ISSUE TITLE
Adding custom modules to Open Berlin configuration

### ISSUE THREAD

**Issue by vbuchhold** [matsim-scenarios/matsim-berlin#33]
With version 5.4, the option to give `RunBerlinScenario.prepareConfig` a list of custom modules (such as `DvrpConfigGroup`) was removed. What is the intended way to extent the Open Berlin Scenario by, e.g., DVRP? Is there a reason why the option to specify custom modules was removed?

**Comment by ikaddoura** [comment]
I think we never had it in the 5.4 version...

You may switch to the (development) branch 5.5.x where we have that option to pass custom modules; see here, for an example how we add custom modules: https://github.com/matsim-scenarios/matsim-berlin/blob/5.5.x/src/main/java/org/matsim/run/drt/RunDrtOpenBerlinScenario.java.

If you want to continue working with the 5.4 version you may also do the following:
```
Config config = prepareConfig( args ) ;
ConfigUtils.addOrGetModule(config, DvrpConfigGroup.class); // !!!
Scenario scenario = prepareScenario( config ) ;
Controler controler = prepareControler( scenario ) ;
controler.run() ;
```

... or call your own `prepareConfig()` instead of calling `RunBerlinScenario.prepareConfig(args)`.

**Comment by vbuchhold** [comment]
In this case, however, DvrpConfigGroup is not filled with the values from the configuration file, right? It seems that I must copy-paste RunBerlinScenario.prepareConfig to use the default parameters for the Open Berlin Scenario. Or is there an option to read and override the configuration values for some modules only? Like:

```
Config config = RunBerlinScenario.prepareConfig(args);
ConfigUtils.addOrGetModule(config, DvrpConfigGroup.class);
// read the configuration file again but set DvrpConfigGroup values only
```

**Comment by ikaddoura** [comment]
Can you please try. We think this should work, i.e. take the values from the configuration file. Let us know if this doesn't work. Thanks!

**Comment by vbuchhold** [comment]
Unfortunately, it does not.

**Comment by kainagel** [comment]
I just wrote a quick test as follows
```
	@Test
	public final void testConfigStatus() {
		{
			// generate a test config that sets two values away from their defaults, and write it to file:
			Config config = ConfigUtils.createConfig();
			DvrpConfigGroup dvrpConfigGroup = ConfigUtils.addOrGetModule( config, DvrpConfigGroup.class );
			dvrpConfigGroup.setTravelTimeEstimationAlpha( 1.23 );
			dvrpConfigGroup.setTravelTimeEstimationBeta( 4.56 );
			ConfigUtils.writeConfig( config, utils.getOutputDirectory() + "ad-hoc-config.xml" );
		}

		{
			// load config file without materializing the drt config group
			Config config = ConfigUtils.loadConfig( new String[] { utils.getOutputDirectory() + "ad-hoc-config.xml"} );

			// materialize the config group
			DvrpConfigGroup dvrpConfig = ConfigUtils.addOrGetModule( config, DvrpConfigGroup.class );

			// check if you are getting back the values from the config file:
			Assert.assertEquals( 1.23, dvrpConfig.getTravelTimeEstimationAlpha(), Double.MIN_VALUE );
			Assert.assertEquals( 4.56., dvrpConfig.getTravelTimeEstimationBeta(), Double.MIN_VALUE );
		}
	}
```
and it passes.  I.e. the approach recovers the values from the file even if the dvrp config group is not materialized from the beginning.  So at this point I am not completely sure what we are talking about.

**Comment by vbuchhold** [comment]
Consider the following `config.xml`:

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
  <module name="multiModeDrt">
    <parameterset type="drt" />
  </module>
</config>
```

Now, the following two variants behave differently:

```
public static void main(String[] args) {
  {
    Config config = ConfigUtils.loadConfig("config.xml", new MultiModeDrtConfigGroup());
    System.out.println(MultiModeDrtConfigGroup.get(config).getModalElements().size());
    // Output: 1
  }
  {
    Config config = ConfigUtils.loadConfig("config.xml");
    ConfigUtils.addOrGetModule(config, MultiModeDrtConfigGroup.class);
    System.out.println(MultiModeDrtConfigGroup.get(config).getModalElements().size());
    // Output: 0
  }
}
```

**Comment by kainagel** [comment]
Argh ... it "materializes" the "normal" settings, but not the parameter sets. Now also https://matsim.atlassian.net/browse/MATSIM-1005 .

If you want to use 5.4.x, I would recommend copy the material from `RunBerlinScenario#prepareConfig`, and put your changes in there, including the necessary `new MultiModeDrtConfgGroup()` when the config is created.  This is, evidently, not desirable in terms of code re-use.  But it is, on the other hand, a relatively small number of lines of code, so I think one can live with it as long as one uses 5.4.x.  5.5.x actually has the passing through of `ConfigModule`s back.

Sorry, this was something I was not aware of.
