### ISSUE TITLE
Full Sim?

### ISSUE THREAD

**Issue by r-barnes** [matsim-scenarios/matsim-berlin#37]
Is there a 100% scenario, or are there instructions for building/running such a scenario anywhere?

**Comment by vsp-gleich** [comment]
As of now, there is no 100% scenario and there are no plans to create one. AFAIK there is no 1-click build script, but here is a paper which describes how the scenario was built: [https://doi.org/10.1016/j.procs.2019.04.120](https://doi.org/10.1016/j.procs.2019.04.120)
