### ISSUE TITLE
some minor bugs in pt schedule

### ISSUE THREAD

**Issue by ikaddoura** [matsim-scenarios/matsim-berlin#4]
There are some minor bugs in the pt schedule. Probably caused by some bugs in the GTFS raw data which was used to generate the MATSim pt schedule:

- U5: weird route between Straußberger Platz und Alexander Platz
- in general: transit lines are split into several parts (several very short routes)
- one can not rely on the transport mode, something like "U-Bahn" is labeled as "bus"
- travel times, frequencies should be more or less ok

**Comment by ikaddoura** [comment]
Ok... the reason is probably that when accessing the GTFS data there was a longterm construction site and the changes in the public transit schedule (bus instead of "U-Bahn" and slightly adjusted route, ...)  were incorporated into the GTFS data.

Not really urgent, but in case this should be fixed: Replace the transit schedule by an updated version or an older version and try to find a GTFS data set without any construction-related changes in the transit schedule. Might be difficult. :-/

**Comment by vsp-gleich** [comment]
TransitSchedule was updated in summer 2019
