### ISSUE TITLE
output plan files have GenericRouteImpl instead of DrtRoutes

### ISSUE THREAD

**Issue by vsp-gleich** [matsim-scenarios/matsim-berlin#46]
Error message is: java.lang.ClassCastException: class org.matsim.core.population.routes.GenericRouteImpl cannot be cast to class org.matsim.contrib.drt.routing.DrtRoute

We already had this a long time ago and fixed it. See [https://github.com/matsim-scenarios/matsim-berlin/blob/17e651107d982bb06642ff8c53fe049698ae47c9/src/main/java/org/matsim/run/RunBerlinScenario.java#L139-L144](https://github.com/matsim-scenarios/matsim-berlin/blob/17e651107d982bb06642ff8c53fe049698ae47c9/src/main/java/org/matsim/run/RunBerlinScenario.java#L139-L144)

Now it fails again.

Obviously we need a test for this.

**Comment by vsp-gleich** [comment]
Update: The issue seems that output plans from (at least 1) matsim-berlin simulations with drt have GenericRouteImpl as route type instead of DrtRoutes. So it's not about reading in plans, but about output plans.

**Comment by tschlenther** [comment]
still up to date?

**Comment by vsp-gleich** [comment]
I just checked a recent output file and it seems to be fixed
