### ISSUE TITLE
A quick question.

### ISSUE THREAD

**Issue by nnzhan** [matsim-scenarios/matsim-berlin#48]
![image](https://user-images.githubusercontent.com/32216158/88374724-d17eec00-cdcc-11ea-9313-f37b697da1f7.png)

After simulation, I saw the number of vehicles peaks around 2:00 am. Why it goes like this?

Thanks

**Comment by ikaddoura** [comment]
difficult to say without more information. Please send me your logfile or tell me what in the default configuration was changed.

**Comment by nnzhan** [comment]
I used the default configuration for 1pt simulation, didn't change anything.

**Comment by ikaddoura** [comment]
hard to tell. can you please provide the logfile of this specific simulation run. thanks!

**Comment by nnzhan** [comment]
how can I send you the log file. thanks

**Comment by ikaddoura** [comment]
I will close this because the last comment is quite some time ago. If you are still struggling with this, please open a new issue under a more specific title and copy paste the logfile (maybe only for the first few iterations).
