### ISSUE TITLE
Running Berlin example with noise extension

### ISSUE THREAD

**Issue by timpuphal** [matsim-scenarios/matsim-berlin#53]
Dear MATSim-team,

I am trying to run the Berlin simulator (https://github.com/matsim-scenarios/matsim-berlin) with the noise extension (https://github.com/matsim-org/matsim-libs). Unfortunately, I could not get it running. The Berlin simulator seems to work only with the MATSim version 12.0-2019w34-SNAPSHOT and the noise extension with version 13.0-SNAPSHOT. I tried different versions for both, but I either have maven install errors or errors when I try to run the Berlin simulator with adding the noise parameters in the config.xml file.

How should I best proceed? I may also post the specific error messages, in case their is no simple solution possible.
Thank you very much in advance.

Best regards,
Tim

**Comment by ikaddoura** [comment]
Hi,
maybe switch from the default branch (5.4.x) to the develop branch: 5.5.x.

The 5.5.x branch uses the 13.0-SNAPSHOT MATSim version. And in the same branch, there is also a run example for the noise extension: https://github.com/matsim-scenarios/matsim-berlin/blob/5.5.x/src/main/java/org/matsim/analysis/RunOfflineNoiseAnalysis.java

**Comment by timpuphal** [comment]
Thank you very much for your fast support! The 5.5.x branch works with the noise extension on my side after some setup. That is great :).

I have two follow-up questions:
1. Is it possible to also do the online noise analysis to make some optimization in MATSim?
2. When I try to build a jar-file out of either RunberlinScenario.java or RunOfflineNoiseAnalysis.java, there are problems with the log4j package (see https://www.nuomiphp.com/eplan/en/228170.html). With the current pom.xml file it seems to not work. Is that problem also happening on your side?

Best regards, 
Tim

**Comment by ikaddoura** [comment]
1. The noise contrib should also provide an example to run the noise computation online (every iteration): https://github.com/matsim-org/matsim-libs/blob/master/contribs/noise/src/main/java/org/matsim/contrib/noise/examples/NoiseOnlineControlerExample.java
There is also a feature which allows to internalize noise costs and charge time dependent and link-specific marginal or average noise cost tolls; have a look into the noise config group!

2. I just tried "mvn clean" and then "mvn -Prelease -DskipTests=true" for the 5.5.x matsim-berlin branch and I don't have any problems building the jar file...

**Comment by timpuphal** [comment]
Thank you very much for your support Ihab!
