### ISSUE TITLE
Building project fails

### ISSUE THREAD

**Issue by Schedulaar** [matsim-scenarios/matsim-berlin#66]
After cloning this repo, building the project using `./mvnw clean package -DskipTests=true` as explained in the README.me fails with the following output:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.github.matsim-scenarios:matsim-berlin >--------------
[INFO] Building MATSim Open Berlin scenario project 5.5.2
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for ch.sbb:matsim-sbb-extensions:jar:12.13 is missing, no dependency information available
[WARNING] The POM for org.processing:core:jar:3.0.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.181 s
[INFO] Finished at: 2021-04-20T13:29:04+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project matsim-berlin: Could not resolve dependencies for project com.github.matsim-scenarios:matsim-berlin:jar:5.5.2: Failure to find ch.sbb:matsim-sbb-extensions:jar:12.13 in https://dl.bintray.com/matsim/matsim was cached in the local repository, resolution will not be reattempted until the update interval of matsim has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I think you moved some dependency away from bintray. Could you fix this?
Thanks a lot!

**Comment by mrieser** [comment]
The problem is, that BinTray shut down on rather short notice, and now some dependencies are no longer available.

For me, it worked by setting the matsim-version in the pom.xml to `13.0-2021w02-SNAPSHOT` (line 14 in the pom).
This uses a newer version of MATSim that does no longer depend on a dependency on BinTray.

**Comment by lubaso** [comment]
@mrieser, I tried that but it did not work for me. Is there a different solution for that issue?

**Comment by lubaso** [comment]
``

> I tried two approaches:
> 
> (1) ... using an IDE, e.g. Eclipse, IntelliJ - Alternative 1: use cloned/downloaded matsim-berlin repository
> 
> I got this error:
> `Could not transfer artifact ch.sbb:matsim-sbb-extensions:pom:12.13 from/to matsim (https://dl.bintray.com/matsim/matsim): Authorization failed for https://dl.bintray.com/matsim/matsim/ch/sbb/matsim-sbb-extensions/12.13/matsim-sbb-extensions-12.13.pom 403 Forbidden`
> 
> (2)... using an IDE, e.g. Eclipse, IntelliJ - Alternative 2: use matsim-berlin as a maven dependency:
> 
> Got these erros:
> `Failure to find ch.sbb:matsim-sbb-extensions:pom:12.13 in https://repo.osgeo.org/repository/release/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo has elapsed or updates are forced`

Solved that as @mrieser suggested. After, I  went to Maven in my IDE (IntelliJ), Lifecycle -> clean and Lifecycle -> install.

**Comment by tschlenther** [comment]
please consider using v5.3 and report back if you have issues. Thank you!
