### ISSUE TITLE
generate a new release with fixed qsim trafficDynamics behavior?

### ISSUE THREAD

**Issue by ikaddoura** [matsim-scenarios/matsim-berlin#68]
In our last release(s), we use the kinematicWaves qsim feature which was recently improved. I suggest, we generate a new matsim-berlin release for a later matsim release (13.0?). @tschlenther @vsp-gleich

**Comment by vsp-gleich** [comment]
I noticed last week that average car speed drops drastically if we replace the 2020w51 release with a recent matsim release. Can this be the cause? It would mean that we have to recalibrate to obtain reasonable results again.

**Comment by ikaddoura** [comment]
drops or increases? the fix mentioned above should result in less road congestion (average car speed should increase)

**Comment by vsp-gleich** [comment]
We have a drop in average car speed from 38.2km/h to 33.5km/h. Car mode share drops down from 34% to 24%. Drt rides are halved, this is what brought me to the issue.

**Comment by vsp-gleich** [comment]
It could be also something else, but it's two runs with identical config, just two different matsim libs versions. Some RunBerlinscenario test also fails due to lower scores, but it's not run by travis because we excluded due to memory reasons.

**Comment by tschlenther** [comment]
i am also still trying to improve the run time when using the new income-dependent scoring parameters. so we will definetely release a 5.3 version anyway and will try to account for everything mentioned here. But we should definetely understand the congestion for before that..

**Comment by tschlenther** [comment]
v5.3 points to a new matsim-version with fixed kinematicWaves and performance improvements for the PersonScoringParams
