### ISSUE TITLE
Alternative 2: use matsim-berlin as a maven dependency 

### ISSUE THREAD

**Issue by lubaso** [matsim-scenarios/matsim-berlin#72]
I'm trying to clone the Berlin Scenario as following:

` ... using an IDE, e.g. Eclipse, IntelliJ - Alternative 2: use matsim-berlin as a maven dependency`

But I get this error:

`Could not find artifact ch.sbb:matsim-sbb-extensions:pom:12.13 in osgeo (https://repo.osgeo.org/repository/release/)`

Any idea on how I can solve that?

Thanks in advance!

**Comment by tschlenther** [comment]
Hi, which version are you referencing in your pom?
Have you tried version 5.5.3 ?
(I just updated the Readme.md, sorry)

**Comment by lubaso** [comment]
@tschlenther, thank you!
