### ISSUE TITLE
github actions: Running the tests (or just chekcinbg the builds) ?

### ISSUE THREAD

**Issue by kt86** [matsim-scenarios/matsim-berlin#81]
I just tried to set up github actions for an other repository based on the stuff I found here in matsim-berlin (because I know, that it was introduced here in #70) 

During that I was/am wondering, if we are running the tests here or if we are only checking the build... ?
For me it looks like 2nd, what is in fact not so good.... Or do we run the tests somewhere else?

![grafik](https://user-images.githubusercontent.com/12124568/134908266-d4e3786e-9e37-46df-8e2a-174cd9b9aca6.png)

I may copy some line of code over here from the other project. But I am **not** an expert, so that configuration is maybe also not good (enough)....

**Comment by vsp-gleich** [comment]
I am not an expert either. But a build just failed due to a failing test. So obviously it does run the tests and it fails if a test fails.
