### ISSUE TITLE
DRT subnetwork filtering is not enabled

### ISSUE THREAD

**Issue by michalmac** [matsim-scenarios/matsim-berlin#83]
I noticed the issue in both DRT configs, where the boolean value should be `true` instead of `drt` (interpreted as `false`):

1. https://github.com/matsim-scenarios/matsim-berlin/blob/d5b2b3d14d5ebac337fcf962db934ea1dee20239/scenarios/berlin-v5.5-1pct/input/drt/berlin-drt-v5.5-1pct.config.xml#L196
2. https://github.com/matsim-scenarios/matsim-berlin/blob/d5b2b3d14d5ebac337fcf962db934ea1dee20239/scenarios/berlin-v5.5-10pct/input/drt/berlin-drt-v5.5-10pct.config.xml#L196

I made the boolean value parsing stricter (reflective config group only), so this kind of errors could be minimised in the future: https://github.com/matsim-org/matsim-libs/pull/1748

**Comment by vsp-gleich** [comment]
Hi, thanks for letting us know! I set the parameter to true on the master branch, so the network should be filtered now. @tschlenther Do you want to adapt the 5.5.3 release or do we leave it as is? I would be ok with both alternatives.
